datasource:
  driver-class-name: "com.mysql.jdbc.Driver"
  url: "jdbc:mysql://52.79.170.80:3306/testdb?useUnicode=true&charaterEncoding=utf-8"
  user-name: "archives"
  password: "coawesome"
  initial-size: 10
  max-active: 10
  max-idle: 10
  min-idle: 10
  max-wait: 3000
